### ISSUE TITLE
crash with hunger overhaul

### ISSUE THREAD

**Issue by ferreiraalex** [luxtracon/floralis#85]
[crash-2023-07-19_18.28.49-client.txt](https://github.com/luxtracon/floralis/files/12096722/crash-2023-07-19_18.28.49-client.txt)

**Comment by luxtracon** [comment]
When hovering over Floralis flower or cactus seeds, hunger overhaul was trying to render a tooltip, but since hunger overhaul checks whether a seed returns a block state and Floralis flower and cactus seeds had no returning block state set, it crashed.

I'm not going to make this a public release yet since I usually don't support that version anymore, if the issue should be reported from other sources as well in the future, I might make it an official release, for now use this patched version.

Also I didn't test through all features and no mod compatability for actual support mods at all, the change might have introduced other issues, but usually it should be fine, so use this file on your own risk.

The .jar is in the .zip, you need to unzip the downloaded file.
[Floralis-1.12.2-1.13.0.zip](https://github.com/luxtracon/floralis/files/12098865/Floralis-1.12.2-1.13.0.zip)

**Comment by ferreiraalex** [comment]
thank you so much! best wishes
